// Import necessary npm modules
const fs = require('fs');
const path = require('path');
const uuid = require('uuid');

// Define function to write a new note to the db.json file
const writeNewNote = (body, notesObj) => { 
    // Create a new note object with a unique id generated by uuid.v4(), using the object spread syntax to copy properties from the 'body' parameter
    const note = { ...body, id: uuid.v4() };
    
    // Push the new note object to the notes array
    notesObj.push(note);
    
    // Write the updated notes array to the db.json file using fs.writeFileSync() and the path module to join the directory name with the file name and location
    fs.writeFileSync(path.join(__dirname, './db/db.json'), JSON.stringify(notesObj, null, 2));
    
    // Return the new note object
    return note;
};

// Define function to remove a note from the db.json file
const removeNote = (id, notesObj) => {
    // Filter out the note with the given id from the notes array, creating a new array with only the remaining notes
    notesObj = notesObj.filter(note => note.id !== id);
    
    // Write the updated notes array to the db.json file using fs.writeFileSync() and the path module to join the directory name with the file name and location
    fs.writeFileSync(path.join(__dirname, './db/db.json'), JSON.stringify(notesObj, null, 2));
};

// Export the writeNewNote and removeNote functions for use in other modules
module.exports = { writeNewNote, removeNote };
