// Importing necessary npm modules
const fs = require('fs');
const path = require('path');
const uuid = require('uuid');

// Function to write a new note to the notes.json file
const writeNewNote = (body, notesObj) => { 
    const note = { ...body, id: uuid.v4() }; // create a new note object with a unique id generated by uuid.v4()
    notesObj.push(note); // push the new note object to the notes array
    fs.writeFileSync(path.join(__dirname, '../db/notes.json'), JSON.stringify(notesObj, null, 2)); // write the updated notes array to the notes.json file
    return note; // return the new note object
};

// Function to remove a note from the notes.json file
const removeNote = (id, notesObj) => {
    notesObj = notesObj.filter(note => note.id !== id); // filter out the note with the given id from the notes array
    fs.writeFileSync(path.join(__dirname, '../db/notes.json'), JSON.stringify(notesObj, null, 2)); // write the updated notes array to the notes.json file
};

// Export the two functions for use in other modules
module.exports = { writeNewNote, removeNote };
